#!/usr/bin/env python3
"""Regenerate docs/events.md from the event registries. `--check` fails if the file is stale."""
from __future__ import annotations

import importlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from wowtools.core.bootstrap import add_vendor_path  # noqa: E402

add_vendor_path()

from wowtools.core.events import LEVELS, SCHEMA_VERSION, TOOL_REGISTRIES  # noqa: E402
from wowtools.tools import TOOLS  # noqa: E402

TARGET = ROOT / "docs" / "events.md"

HEADER = f"""# Event log reference

> Generated by `python3 scripts/gen_event_docs.py`. Do not edit by hand.

Each tool logs to its own folder, `logs/<tool>/` (for example `logs/wtf-cleaner/`). The launcher and the tool
picker use `logs/suite/`. Each folder holds two files per day:

- `events-YYYY-MM-DD.log`: one JSON object per line, **all** levels (source of truth).
- `logfile-YYYY-MM-DD.log`: the same events as readable lines, filtered by `[general] log_level`.

Files older than `[general] log_retention_days` (default 90) are deleted at start-up. Logs in the older flat
layout (`logs/events-*.jsonl`, `logs/wow-tools-*.log`) are split into the tool folders at start-up.

## Envelope (schema v{SCHEMA_VERSION})

| Field | Meaning |
|---|---|
| `v` | Schema version. Only changes when envelope fields change meaning. |
| `ts` | Local time, ISO-8601 with UTC offset and milliseconds. |
| `session` | 8 hex characters, one per launch. Group a run's events by this. |
| `suite_version` | `wowtools.__version__`. |
| `tool` | `suite` (launcher / picker) or the tool name, e.g. `wtf-cleaner`. |
| `mode` | `tui` or `cli`. |
| `event` | Dotted name from the tables below. |
| `level` | {", ".join(f"`{name}`" for name in LEVELS)}. Fixed per event; a caller may only raise it. |
| `dry_run` | `true`/`false` where it matters, otherwise `null`. |
| `data` | Event-specific fields. New fields may be added at any time. |

## Adding events to a tool

Declare them in `wowtools/tools/<tool>/events.py` as `EVENTS = {{"name": EventSpec(level, description)}}`
and call `register_events(TOOL_NAME, EVENTS)` there; import that module from the tool package's
`__init__.py`. Then call `log_event("name", **data)`. Regenerate this file and commit it.
"""


def render() -> str:
    for tool in TOOLS.values():
        importlib.import_module(tool.module.rsplit(".", 1)[0])
    parts = [HEADER]
    for owner, events in TOOL_REGISTRIES.items():
        if owner.startswith("test-"):
            continue
        parts.append(f"\n## `{owner}` events\n\n| Event | Level | Description |\n|---|---|---|\n")
        for name in sorted(events):
            spec = events[name]
            parts.append(f"| `{name}` | {spec.level} | {spec.description} |\n")
    return "".join(parts)


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != text:
            print("docs/events.md is out of date. Run: python3 scripts/gen_event_docs.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(text, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
