#!/usr/bin/env python3
"""Rebuild vendor/ from requirements.lock (pinned versions with SHA-256 hashes). Run from anywhere:

    python3 scripts/update_vendor.py --lock   # after editing requirements.txt: refresh requirements.lock's hashes
    python3 scripts/update_vendor.py          # reinstall vendor/ (pip --require-hashes)

See docs/vendoring.md."""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path
from typing import Callable

ROOT = Path(__file__).resolve().parents[1]
VENDOR = ROOT / "vendor"
REQUIREMENTS = ROOT / "requirements.txt"
LOCK = ROOT / "requirements.lock"
NATIVE_SUFFIXES = {".so", ".pyd", ".dll", ".dylib"}
_PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([A-Za-z0-9.+!_-]+)$")
_LOCK_PIN_RE = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([A-Za-z0-9.+!_-]+)\s*\\?\s*$")
LOCK_HEADER = ("# Generated by: python3 scripts/update_vendor.py --lock (from requirements.txt). Do not edit by hand.\n"
               "# One SHA-256 per pure-Python wheel; vendor/ is installed with pip --require-hashes.\n")

FileLister = Callable[[str, str], list]


def _normalize(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def parse_pins(text: str) -> list[tuple[str, str]]:
    """requirements.txt lines as (name, version). Every requirement must be an exact == pin."""
    pins = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        match = _PIN_RE.match(line)
        if not match:
            raise SystemExit(f"requirements.txt: {line!r} is not pinned with ==")
        pins.append((match.group(1), match.group(2)))
    return pins


def lock_pins(text: str) -> list[tuple[str, str]]:
    return [(m.group(1), m.group(2)) for line in text.splitlines() if (m := _LOCK_PIN_RE.match(line.strip()))]


def check_lock(pins: list[tuple[str, str]], lock_text: str) -> None:
    want = sorted((_normalize(n), v) for n, v in pins)
    have = sorted((_normalize(n), v) for n, v in lock_pins(lock_text))
    if want != have:
        raise SystemExit("requirements.lock does not match requirements.txt. "
                         "Run: python3 scripts/update_vendor.py --lock")


def pypi_files(name: str, version: str) -> list:
    """The release's files from PyPI's JSON API (filename, packagetype, digests)."""
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    with urllib.request.urlopen(url, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))["urls"]


def render_lock(pins: list[tuple[str, str]], files: FileLister = pypi_files) -> str:
    """requirements.lock text: each pin with the hashes of its pure-Python (none-any) wheels."""
    blocks = []
    for name, version in pins:
        hashes = sorted(f["digests"]["sha256"] for f in files(name, version)
                        if f.get("packagetype") == "bdist_wheel" and f.get("filename", "").endswith("-none-any.whl"))
        if not hashes:
            raise SystemExit(f"{name}=={version} has no pure-Python wheel on PyPI")
        blocks.append(f"{name}=={version} \\\n" + " \\\n".join(f"    --hash=sha256:{h}" for h in hashes) + "\n")
    return LOCK_HEADER + "".join(blocks)


def write_lock() -> int:
    pins = parse_pins(REQUIREMENTS.read_text(encoding="utf-8"))
    LOCK.write_text(render_lock(pins), encoding="utf-8", newline="\n")
    print(f"{LOCK} written ({len(pins)} packages). Now run: python3 scripts/update_vendor.py")
    return 0


def rebuild() -> int:
    check_lock(parse_pins(REQUIREMENTS.read_text(encoding="utf-8")), LOCK.read_text(encoding="utf-8"))
    if VENDOR.exists():
        shutil.rmtree(VENDOR)
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "--target", str(VENDOR), "--no-compile",
         "--no-deps", "--only-binary=:all:", "--require-hashes", "-r", str(LOCK)],
        check=True,
    )
    shutil.rmtree(VENDOR / "bin", ignore_errors=True)
    for cache in list(VENDOR.rglob("__pycache__")):
        shutil.rmtree(cache, ignore_errors=True)
    native = [p for p in VENDOR.rglob("*") if p.suffix.lower() in NATIVE_SUFFIXES]
    if native:
        print("vendor/ must be pure Python, but native files were installed:", file=sys.stderr)
        for path in native:
            print(f"  {path}", file=sys.stderr)
        return 1
    print(f"vendor/ rebuilt from {LOCK}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Rebuild vendor/ from the hashed requirements.lock.")
    parser.add_argument("--lock", action="store_true",
                        help="refresh requirements.lock from requirements.txt (looks the hashes up on PyPI)")
    args = parser.parse_args(argv)
    return write_lock() if args.lock else rebuild()


if __name__ == "__main__":
    sys.exit(main())
